nginx_linuxwt:
    restart: always
    image: nginx:1.15
    container_name: nginx_linuxwt
    volumes:
        - ./html:/www/html
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx_flask.conf:/etc/nginx/conf.d/default.conf
        - /etc/localtime:/etc/localtime
        - /etc/timezone:/etc/timezone
    privileged: true
    ports:
       - "80:80"
