redis:
  restart: always
  image: redis:latest
  container_name: redis
  privileged: true
  volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  ports: 
      - 6389:6379
  command: ["redis-server", "--requirepass", "redispassword", "--appendonly", "yes"]
